"""update to uuid 21

Revision ID: 06fac9ea2d89
Revises: 745d98c66af9
Create Date: 2025-06-11 20:06:31.166980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06fac9ea2d89'
down_revision: Union[str, None] = '745d98c66af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('results', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_constraint('results_place_id_fkey', 'results', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('results_place_id_fkey', 'results', 'places', ['place_id'], ['id'], ondelete='SET NULL')
    op.alter_column('results', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
