"""update to uuid 3

Revision ID: 0ca28e7f487a
Revises: ecae0de581e3
Create Date: 2025-06-11 12:08:33.601595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca28e7f487a'
down_revision: Union[str, None] = 'ecae0de581e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('results', 'event_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=True,
                    postgresql_using='event_id::uuid'
                    )
    op.alter_column('students_events', 'event_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False,
                    postgresql_using='event_id::uuid'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students_events', 'event_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
                    postgresql_using='event_id::varchar')
    op.alter_column('results', 'event_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
                    postgresql_using='event_id::varchar'
                    )
    # ### end Alembic commands ###
