"""update to uuid 11

Revision ID: 1019a5bb5b33
Revises: 1babe41e3875
Create Date: 2025-06-11 19:23:41.175961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1019a5bb5b33'
down_revision: Union[str, None] = '1babe41e3875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students_events')
    op.drop_constraint('results_student_id_fkey', 'results', type_='foreignkey')
    op.alter_column('student_profiles', 'student_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('student_profiles', 'coach_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_profiles', 'coach_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('student_profiles', 'student_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_foreign_key('results_student_id_fkey', 'results', 'student_profiles', ['student_id'], ['student_id'], ondelete='SET NULL')
    op.create_table('students_events',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='students_events_event_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], name='students_events_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'event_id', name='students_events_pkey')
    )
    # ### end Alembic commands ###
