"""update to uuid 10

Revision ID: 1babe41e3875
Revises: b89e13837c8c
Create Date: 2025-06-11 19:20:16.224340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1babe41e3875'
down_revision: Union[str, None] = 'b89e13837c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_constraint('events_coach_id_fkey', 'events', type_='foreignkey')
    op.drop_constraint('groups_coach_id_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('reset_password_codes_user_id_fkey', 'reset_password_codes', type_='foreignkey')
    op.add_column('student_profiles', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('student_profiles', 'coach_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('student_profiles_student_id_fkey', 'student_profiles', type_='foreignkey')
    op.drop_constraint('student_profiles_coach_id_fkey', 'student_profiles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('student_profiles_coach_id_fkey', 'student_profiles', 'users', ['coach_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('student_profiles_student_id_fkey', 'student_profiles', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('student_profiles', 'coach_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('student_profiles', 'id')
    op.create_foreign_key('reset_password_codes_user_id_fkey', 'reset_password_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_coach_id_fkey', 'groups', 'users', ['coach_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('events_coach_id_fkey', 'events', 'users', ['coach_id'], ['id'], ondelete='SET NULL')
    op.create_table('user_roles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_roles_role_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_roles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name='user_roles_pkey')
    )
    # ### end Alembic commands ###
