"""add category table 2

Revision ID: 2518673646a0
Revises: a8ec8f878b55
Create Date: 2025-06-14 17:18:33.903438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2518673646a0'
down_revision: Union[str, None] = 'a8ec8f878b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('age_categories', sa.Column('gender_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'age_categories', 'genders', ['gender_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'age_categories', type_='foreignkey')
    op.drop_column('age_categories', 'gender_id')
    # ### end Alembic commands ###
