"""migrate in postgresql 3

Revision ID: 291661d2fbe1
Revises: 875ca1663cd7
Create Date: 2025-06-11 10:54:16.515348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291661d2fbe1'
down_revision: Union[str, None] = '875ca1663cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_types', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
                    postgresql_using='id::uuid')
    op.alter_column('events', 'type_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=True,
                    postgresql_using='type_id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'type_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True,
                    postgresql_using='type_id::varchar')
    op.alter_column('event_types', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
                    postgresql_using='id::varchar')
    # ### end Alembic commands ###
