"""update to uuid 6

Revision ID: 3c4677643642
Revises: 70524749b031
Create Date: 2025-06-11 12:29:41.860691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4677643642'
down_revision: Union[str, None] = '70524749b031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_profiles_group_id_fkey', 'student_profiles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('student_profiles_group_id_fkey', 'student_profiles', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
