"""add table attendance

Revision ID: 46f799e0a990
Revises: 4dc80c76840d
Create Date: 2025-06-12 18:04:24.664143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f799e0a990'
down_revision: Union[str, None] = '4dc80c76840d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('attendance',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('training_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'training_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_table('attendance_statuses')
    # ### end Alembic commands ###
