"""add table attendance rel

Revision ID: 668cb66d4855
Revises: 46f799e0a990
Create Date: 2025-06-12 18:05:54.721473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668cb66d4855'
down_revision: Union[str, None] = '46f799e0a990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'attendance', 'attendance_statuses', ['status_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('trainings_coach_id_fkey', 'trainings', type_='foreignkey')
    op.create_foreign_key(None, 'trainings', 'coach_profiles', ['coach_id'], ['coach_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainings', type_='foreignkey')
    op.create_foreign_key('trainings_coach_id_fkey', 'trainings', 'coach_profiles', ['coach_id'], ['coach_id'], ondelete='SET NULL')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    # ### end Alembic commands ###
