"""update to uuid 5

Revision ID: 70524749b031
Revises: 8dbbebe6cfc2
Create Date: 2025-06-11 12:18:48.960276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70524749b031'
down_revision: Union[str, None] = '8dbbebe6cfc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'results', 'events', ['event_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'students_events', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students_events', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    # ### end Alembic commands ###
