"""add fields in student profile

Revision ID: 7d6c4e6ff701
Revises: b9ed51d9e6a5
Create Date: 2025-06-12 17:14:17.996087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6c4e6ff701'
down_revision: Union[str, None] = 'b9ed51d9e6a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('level_id', sa.UUID(), nullable=True))
    op.add_column('student_profiles', sa.Column('weight', sa.String(length=5), nullable=True))
    op.add_column('student_profiles', sa.Column('first_coach', sa.String(length=100), nullable=True))
    op.add_column('student_profiles', sa.Column('medical_permit', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'student_profiles', 'sports_levels', ['level_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_column('student_profiles', 'medical_permit')
    op.drop_column('student_profiles', 'first_coach')
    op.drop_column('student_profiles', 'weight')
    op.drop_column('student_profiles', 'level_id')
    # ### end Alembic commands ###
