"""update to uuid 13

Revision ID: 80234bf41df1
Revises: c51a61449dc5
Create Date: 2025-06-11 19:26:22.746950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80234bf41df1'
down_revision: Union[str, None] = 'c51a61449dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN id DROP DEFAULT")
    op.alter_column('events', 'coach_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=True,
                    postgresql_using='coach_id::uuid')
    op.alter_column('groups', 'coach_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=True,
                    postgresql_using='coach_id::uuid')
    op.alter_column('results', 'student_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=True,
                    postgresql_using='student_id::uuid')
    op.alter_column('student_profiles', 'student_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False,
                    postgresql_using='student_id::uuid')
    op.alter_column('student_profiles', 'coach_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False,
                    postgresql_using='coach_id::uuid')
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
                    postgresql_using='id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               postgresql_using='id::varchar')
    op.alter_column('student_profiles', 'coach_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
                    postgresql_using='coach_id::varchar')
    op.alter_column('student_profiles', 'student_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
                    postgresql_using='student_id::varchar')
    op.alter_column('results', 'student_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
                    postgresql_using='student_id::varchar')
    op.alter_column('groups', 'coach_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
                    postgresql_using='coach_id::varchar')
    op.alter_column('events', 'coach_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
                    postgresql_using='coach_id::varchar')
    # ### end Alembic commands ###
