"""update to uuid 1

Revision ID: 817b0034991b
Revises: 1976ced8df8a
Create Date: 2025-06-11 11:52:14.917431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '817b0034991b'
down_revision: Union[str, None] = '1976ced8df8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('results_event_id_fkey', 'results', type_='foreignkey')
    op.drop_constraint('students_events_event_id_fkey', 'students_events', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('students_events_event_id_fkey', 'students_events', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('results_event_id_fkey', 'results', 'events', ['event_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
