"""second migrate in postgresql

Revision ID: 875ca1663cd7
Revises: 7c46d302f1b7
Create Date: 2025-06-11 10:52:59.079343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875ca1663cd7'
down_revision: Union[str, None] = '7c46d302f1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_type_id_fkey', 'events', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('events_type_id_fkey', 'events', 'event_types', ['type_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
