"""update to uuid 16

Revision ID: 8d1620e496d0
Revises: 31aca7e0f8fc
Create Date: 2025-06-11 19:50:30.054536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1620e496d0'
down_revision: Union[str, None] = '31aca7e0f8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'reset_password_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('roles', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'reset_password_codes', type_='foreignkey')
    # ### end Alembic commands ###
