"""update to uuid 4

Revision ID: 8dbbebe6cfc2
Revises: 0ca28e7f487a
Create Date: 2025-06-11 12:09:36.073286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbbebe6cfc2'
down_revision: Union[str, None] = '0ca28e7f487a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE events ALTER COLUMN id DROP DEFAULT")
    op.alter_column('events', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
                    postgresql_using='id::varchar')
    # ### end Alembic commands ###
