"""edit users rel 2

Revision ID: 8fe5cb487145
Revises: 23bc2d8eeb78
Create Date: 2025-06-12 17:35:27.996174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe5cb487145'
down_revision: Union[str, None] = '23bc2d8eeb78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_coach_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'coach_id')
    op.drop_constraint('groups_coach_id_fkey', 'groups', type_='foreignkey')
    op.drop_column('groups', 'coach_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('coach_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('groups_coach_id_fkey', 'groups', 'users', ['coach_id'], ['id'], ondelete='SET NULL')
    op.add_column('events', sa.Column('coach_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('events_coach_id_fkey', 'events', 'users', ['coach_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
