"""add payment info

Revision ID: 94bdfa5598bf
Revises: 8e9195cad19d
Create Date: 2025-06-13 18:06:21.719626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94bdfa5598bf'
down_revision: Union[str, None] = '8e9195cad19d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('external_payment_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('organizations', sa.Column('payment_provider', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('payment_account_id', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('payment_secret_key', sa.String(length=200), nullable=True))
    op.add_column('organizations', sa.Column('tax_system_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'tax_system_code')
    op.drop_column('organizations', 'payment_secret_key')
    op.drop_column('organizations', 'payment_account_id')
    op.drop_column('organizations', 'payment_provider')
    op.drop_table('training_payments')
    # ### end Alembic commands ###
