"""update to uuid 27

Revision ID: 9900cf897d2c
Revises: 91875303d19f
Create Date: 2025-06-11 20:12:49.154529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9900cf897d2c'
down_revision: Union[str, None] = '91875303d19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE reset_password_codes ALTER COLUMN id DROP DEFAULT")
    op.alter_column('reset_password_codes', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reset_password_codes', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               postgresql_using='id::varchar')
    # ### end Alembic commands ###
