"""add category table 1

Revision ID: a8ec8f878b55
Revises: e962f455d23f
Create Date: 2025-06-14 17:09:52.746426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ec8f878b55'
down_revision: Union[str, None] = 'e962f455d23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('age_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('sport_type_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sport_type_id'], ['sport_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weight_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('max_weight', sa.Integer(), nullable=True),
    sa.Column('age_category_id', sa.UUID(), nullable=False),
    sa.Column('gender_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['age_category_id'], ['age_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight_categories')
    op.drop_table('age_categories')
    op.drop_table('genders')
    # ### end Alembic commands ###
