"""update to uuid 9

Revision ID: b89e13837c8c
Revises: f65ace4ae68b
Create Date: 2025-06-11 12:33:55.942556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b89e13837c8c'
down_revision: Union[str, None] = 'f65ace4ae68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'student_profiles', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    # ### end Alembic commands ###
