"""edit users rel 3

Revision ID: c3c05a95c6d3
Revises: 8fe5cb487145
Create Date: 2025-06-12 17:36:02.967116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c05a95c6d3'
down_revision: Union[str, None] = '8fe5cb487145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('coach_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'events', 'coach_profiles', ['coach_id'], ['coach_id'], ondelete='SET NULL')
    op.add_column('groups', sa.Column('coach_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'groups', 'coach_profiles', ['coach_id'], ['coach_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'coach_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'coach_id')
    # ### end Alembic commands ###
