"""add category table 4

Revision ID: e012920e571d
Revises: e4fa8546c3c7
Create Date: 2025-06-15 14:11:34.632084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e012920e571d'
down_revision: Union[str, None] = 'e4fa8546c3c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('karate_kumite_results_place_id_fkey', 'karate_kumite_results', type_='foreignkey')
    op.drop_column('karate_kumite_results', 'place_id')
    op.add_column('results', sa.Column('place_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'results', 'places', ['place_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_column('results', 'place_id')
    op.add_column('karate_kumite_results', sa.Column('place_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('karate_kumite_results_place_id_fkey', 'karate_kumite_results', 'places', ['place_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
