"""add category table 3

Revision ID: e4fa8546c3c7
Revises: 2518673646a0
Create Date: 2025-06-15 14:10:44.964437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4fa8546c3c7'
down_revision: Union[str, None] = '2518673646a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('age_category_id', sa.UUID(), nullable=False))
    op.add_column('results', sa.Column('weight_category_id', sa.UUID(), nullable=True))
    op.add_column('results', sa.Column('visited', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'results', 'weight_categories', ['weight_category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'results', 'age_categories', ['age_category_id'], ['id'], ondelete='RESTRICT')
    op.add_column('users', sa.Column('gender_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'genders', ['gender_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'gender_id')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_column('results', 'visited')
    op.drop_column('results', 'weight_category_id')
    op.drop_column('results', 'age_category_id')
    # ### end Alembic commands ###
