"""update to uuid 8

Revision ID: f65ace4ae68b
Revises: 983bac7aa7a6
Create Date: 2025-06-11 12:30:34.741270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65ace4ae68b'
down_revision: Union[str, None] = '983bac7aa7a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE groups ALTER COLUMN id DROP DEFAULT")
    op.alter_column('groups', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    op.alter_column('student_profiles', 'group_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=True,
                    postgresql_using='group_id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_profiles', 'group_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
                    postgresql_using='id::varchar')
    op.alter_column('groups', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               postgresql_using='id::varchar')
    # ### end Alembic commands ###
